"""Add comment_count to Prompt

Revision ID: d09b37a83565
Revises: 20260121_0949
Create Date: 2026-02-08 00:36:12.717200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd09b37a83565'
down_revision: Union[str, None] = '20260121_0949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('supports_api_key', sa.Boolean(), nullable=False),
    sa.Column('supports_oauth', sa.Boolean(), nullable=False),
    sa.Column('supports_manual', sa.Boolean(), nullable=False),
    sa.Column('api_endpoint', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('auth_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('documentation_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_index(op.f('ix_providers_slug'), 'providers', ['slug'], unique=True)
    op.create_table('account_connections',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('connection_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_connections_connection_type'), 'account_connections', ['connection_type'], unique=False)
    op.create_index(op.f('ix_account_connections_provider_id'), 'account_connections', ['provider_id'], unique=False)
    op.create_index(op.f('ix_account_connections_status'), 'account_connections', ['status'], unique=False)
    op.create_index(op.f('ix_account_connections_user_id'), 'account_connections', ['user_id'], unique=False)
    op.create_table('credential_vault_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_data', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['account_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credential_vault_items_connection_id'), 'credential_vault_items', ['connection_id'], unique=False)
    op.create_table('manual_overrides',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['account_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_overrides_connection_id'), 'manual_overrides', ['connection_id'], unique=False)
    op.alter_column('creator_payouts', 'billing_month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_payouts_creator'), table_name='creator_payouts')
    op.drop_index(op.f('idx_payouts_status'), table_name='creator_payouts')
    op.create_index(op.f('ix_creator_payouts_creator_id'), 'creator_payouts', ['creator_id'], unique=False)
    op.drop_constraint(None, 'creator_payouts', type_='foreignkey')
    op.create_foreign_key(None, 'creator_payouts', 'users', ['creator_id'], ['id'])
    op.alter_column('flow_copies', 'billing_month',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_copies_billing'), table_name='flow_copies')
    op.drop_index(op.f('idx_copies_creator'), table_name='flow_copies')
    op.drop_index(op.f('idx_copies_user_month'), table_name='flow_copies')
    op.create_index(op.f('ix_flow_copies_creator_id'), 'flow_copies', ['creator_id'], unique=False)
    op.create_index(op.f('ix_flow_copies_flow_id'), 'flow_copies', ['flow_id'], unique=False)
    op.create_index(op.f('ix_flow_copies_user_id'), 'flow_copies', ['user_id'], unique=False)
    op.drop_constraint(None, 'flow_copies', type_='foreignkey')
    op.drop_constraint(None, 'flow_copies', type_='foreignkey')
    op.create_foreign_key(None, 'flow_copies', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'flow_copies', 'prompts', ['flow_id'], ['id'])
    op.add_column('prompts', sa.Column('comment_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_prompts_premium'), table_name='prompts')
    op.drop_index(op.f('idx_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('idx_subscriptions_stripe'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_users_stripe_connect'), table_name='users')
    op.drop_index(op.f('idx_users_stripe_customer'), table_name='users')
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.create_index(op.f('idx_users_stripe_customer'), 'users', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('idx_users_stripe_connect'), 'users', ['stripe_connect_id'], unique=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.create_index(op.f('idx_subscriptions_stripe'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('idx_prompts_premium'), 'prompts', ['is_premium', 'featured'], unique=False)
    op.drop_column('prompts', 'comment_count')
    op.drop_constraint(None, 'flow_copies', type_='foreignkey')
    op.drop_constraint(None, 'flow_copies', type_='foreignkey')
    op.create_foreign_key(None, 'flow_copies', 'prompts', ['flow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'flow_copies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_flow_copies_user_id'), table_name='flow_copies')
    op.drop_index(op.f('ix_flow_copies_flow_id'), table_name='flow_copies')
    op.drop_index(op.f('ix_flow_copies_creator_id'), table_name='flow_copies')
    op.create_index(op.f('idx_copies_user_month'), 'flow_copies', ['user_id', 'billing_month'], unique=False)
    op.create_index(op.f('idx_copies_creator'), 'flow_copies', ['creator_id', 'billing_month'], unique=False)
    op.create_index(op.f('idx_copies_billing'), 'flow_copies', ['billing_month', 'counted_for_payout'], unique=False)
    op.alter_column('flow_copies', 'billing_month',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'creator_payouts', type_='foreignkey')
    op.create_foreign_key(None, 'creator_payouts', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_creator_payouts_creator_id'), table_name='creator_payouts')
    op.create_index(op.f('idx_payouts_status'), 'creator_payouts', ['status', 'billing_month'], unique=False)
    op.create_index(op.f('idx_payouts_creator'), 'creator_payouts', ['creator_id', 'billing_month'], unique=False)
    op.alter_column('creator_payouts', 'billing_month',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_manual_overrides_connection_id'), table_name='manual_overrides')
    op.drop_table('manual_overrides')
    op.drop_index(op.f('ix_credential_vault_items_connection_id'), table_name='credential_vault_items')
    op.drop_table('credential_vault_items')
    op.drop_index(op.f('ix_account_connections_user_id'), table_name='account_connections')
    op.drop_index(op.f('ix_account_connections_status'), table_name='account_connections')
    op.drop_index(op.f('ix_account_connections_provider_id'), table_name='account_connections')
    op.drop_index(op.f('ix_account_connections_connection_type'), table_name='account_connections')
    op.drop_table('account_connections')
    op.drop_index(op.f('ix_providers_slug'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
